services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=contacts'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: